# Generated by Django 6.0.1 on 2026-02-02 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('category', models.CharField(choices=[('exercise', '運動'), ('care', 'お世話')], max_length=20, verbose_name='カテゴリ')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='実施日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='達成フラグ')),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='サボり理由')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.quest')),
            ],
            options={
                'unique_together': {('user', 'quest', 'date')},
            },
        ),
    ]
