# Generated by Django 6.0.1 on 2026-02-04 05:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('user', 'quest', 'date', 'is_completed', 'failure_reason')},
        ),
    ]
